DOMAIN = "http://127.0.0.1"
PORT = "8000"
CHAT_STREAM_URL = f"{DOMAIN}:{PORT}/chat/stream"
SYMPTOM_CHECKER_STREAM_URL = f"{DOMAIN}:{PORT}/symptom_checker/stream"
LAB_REPORT_ANALYSIS_STREAM_URL = f"{DOMAIN}:{PORT}/lab_report_analysis/stream"