"""Add profile picture and other information to User model

Revision ID: 7c1581ed7737
Revises: 
Create Date: 2025-10-11 23:21:51.770485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1581ed7737'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chronic_conditions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('chronic_conditions')
        batch_op.drop_column('allergies')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
